### ISSUE TITLE
Can you tell me what the URL points 

### ISSUE THREAD

**Issue by crazywang123** [amjal/Smart-Irrigation-using-Reinforcement-Learning#1]
def __init__(self, t, policy, min_moisture, max_moisture, measures, url):

**Comment by amjal** [comment]
Hi, 
I was developing field devices along with this project. The URL points to a simple PHP code my friend developed. Field devices would read soil moisture values from sensors and update a record by sending requests to that code. The agent residing on a server itself would read the measures and update the Q values, make a decision and send it to the PHP code. Then field devices would request to read the decision and take action by giving some current to a pump using PWM. Of course, the current would have to be amplified, etc.
